---
deployment:
  tasks:
    - export REPOPATH=/home/nteagvxe/repositories/portfolio-website
    - export DEPLOYPATH=/home/nteagvxe/public_html/
    - echo "Deploying to $DEPLOYPATH"
    - cd $REPOPATH
    - git pull
    - make install && make build
    - cp -r app/build/ $DEPLOYPATH
    - cd $DEPLOYPATH && npm install -g serve && serve -s
