---
deployment:
  tasks:
    - export REPOPATH=/home/nteagvxe/repositories/portfolio-website
    - export DEPLOYPATH=/home/nteagvxe/public_html/
    - echo "Deploying to $DEPLOYPATH"
    - cd $REPOPATH && make deploy_manual
    - export HEXTOOLPATH=/home/nteagvxe/public_hextool_html
    - echo "Deploying hex tool to $HEXTOOLPATH"
    - cd $REPOPATH && make deploy_hextool
